# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: A
  jobs:
  - job: A1
    steps:
    - bash: echo "A1 success"    
  - job: A2
    dependsOn: A1
    steps:
    - bash: echo "A2 success"
  - job: A3
    dependsOn: A2
    steps:
    - bash: echo "A3 success"

- stage: B
  jobs:
  - job: B1
    steps:
    - bash: echo "B1 success"    
  - job: B2
    dependsOn: B1
    steps:
    - bash: echo "B2 success"
  - job: B3
    dependsOn: B2
    steps:
    - bash: echo "B3 success"

- stage: C
  jobs:
  - job: C1    
    steps:
    - bash: echo "C1 success"    
  - job: C2
    dependsOn: C1
    steps:
    - bash: echo "C2 success"
  - job: C3
    dependsOn: C2
    steps:
    - bash: echo "C3 success"